let project = new Project('New Project');
project.addAssets('Assets/**');
project.addShaders('Shaders/**');
project.addSources('Sources');
project.addLibrary('/home/jsnadeau/foundsdk/hscript');
project.addLibrary('/home/jsnadeau/foundsdk/haxeui-core');
project.addLibrary('/home/jsnadeau/foundsdk/haxeui-kha');
project.addLibrary('/home/jsnadeau/foundsdk/haxeui-kha-extended');
project.addLibrary('/home/jsnadeau/foundsdk/foundry');
project.addLibrary('/home/jsnadeau/foundsdk/iron');
project.addDefine('foundry_editor');
resolve(project);
